# 当前启用的数据源
sources:
  - id: "toutiao"
    name: "今日头条"
  - id: "thepaper"
    name: "澎湃新闻"
  - id: "sputniknewscn"
    name: "卫星通讯社"
  - id: "zaobao"
    name: "联合早报"
  - id: "kaopu"
    name: "靠谱新闻"
  - id: "wallstreetcn-hot"
    name: "华尔街见闻"
  - id: "wallstreetcn-news"
    name: "华尔街见闻快讯"
  - id: "cls-hot"
    name: "财联社"
  - id: "cls-depth"
    name: "财联社-深度"
  - id: "gelonghui"
    name: "格隆汇"
  - id: "fastbull-news"
    name: "法布财经"
  - id: "ithome"
    name: "IT之家"
  - id: "juejin"
    name: "掘金"
  - id: "hackernews"
    name: "Hacker News"
  - id: "solidot"
    name: "Solidot"